**420-A58-SF - Algorithmes d'apprentissage non supervisé - Hiver 2023 - Spécialisation technique en Intelligence Artificielle**<br/>
MIT License - Copyright (c) 2023 Mikaël Swawola
<br/>

---
# Tutorat - Systèmes de recommandation

On considère la matrice d'utilité Y ci-dessous. Les notes sont données par les utilisateurs Alice, Bob et Eve sur une échelle de 1 à 5. Les produits notés sont nommés a,b,c,d,e,f,g et h.

|   | Alice  | Bob  | Eve  |
|---|---|---|---|
| a  | 4   |   | 2  |
| b  | 5  | 3  |   |
| c  |   | 4  | 1  |
| d  | 5  | 3  | 3  |
| e  | 1  | 1  |   |
| f  |   | 2  | 4  |
| g  | 3  | 1  | 5  |
| h  | 2  |   | 3  |

### Question 1 - À l'aide de Numpy, définir les tableaux `Y` et `R` correspondant à la matrice d'utilité ci-dessus. Afficher ces deux tableaux à l'aide la commande `print`.

### ----- Votre réponse ci-dessous -----

In [19]:
import numpy as np

In [42]:
Y = np.array([[4, 0, 2], 
              [5, 3, 0], 
              [0, 4, 1], 
              [5, 3, 3], 
              [1, 1, 0], 
              [0, 2, 4], 
              [3, 1, 5], 
              [2, 0, 3]])
Y

array([[4, 0, 2],
       [5, 3, 0],
       [0, 4, 1],
       [5, 3, 3],
       [1, 1, 0],
       [0, 2, 4],
       [3, 1, 5],
       [2, 0, 3]])

In [27]:
print(f'Y={Y}')

Y=[[4 0 2]
 [5 3 0]
 [0 4 1]
 [5 3 3]
 [1 1 0]
 [0 2 4]
 [3 1 5]
 [2 0 3]]


In [40]:
R = np.array([[1, 0, 1], 
              [1, 1, 0], 
              [0, 1, 1], 
              [1, 1, 1], 
              [1, 1, 0], 
              [0, 1, 1], 
              [1, 1, 1], 
              [1, 0, 1]])
R

array([[1, 0, 1],
       [1, 1, 0],
       [0, 1, 1],
       [1, 1, 1],
       [1, 1, 0],
       [0, 1, 1],
       [1, 1, 1],
       [1, 0, 1]])

In [41]:
print(f'R={R}')

R=[[1 0 1]
 [1 1 0]
 [0 1 1]
 [1 1 1]
 [1 1 0]
 [0 1 1]
 [1 1 1]
 [1 0 1]]


In [31]:
np.digitize(Y, [0], right=True)

array([[1, 0, 1],
       [1, 1, 0],
       [0, 1, 1],
       [1, 1, 1],
       [1, 1, 0],
       [0, 1, 1],
       [1, 1, 1],
       [1, 0, 1]])

### Question 2 - Initialiser les variables `n_produits` et `n_utilisateurs` correspondant respectivement au nombre de produits et au nombre d'utilisateurs.

### ----- Votre réponse ci-dessous -----

In [24]:
n_produits = Y.shape[0]
n_produits

8

In [25]:
n_utilisateurs = Y.shape[1]
n_utilisateurs

3

### Question 3 - Normaliser la matrice `Y` en soustrayant chaque note de la matrice d'utilité par le moyenne des notes pour chaque produit. Nommez la matrice normalisée `Y_norm`. Afficher `Y_norm` à l'aide de la commande `print`.

### ----- Votre réponse ci-dessous -----

In [66]:
# La moyenne de la première ligne
Y[0,:].sum() / R[0,:].sum()

3.0

***Forma 1 de calcular Y_norm***

In [67]:
nombre = R.sum(axis=1)
somme = Y.sum(axis=1)
moyenne = (somme / nombre).reshape(-1,1)
moyenne

array([[3.        ],
       [4.        ],
       [2.5       ],
       [3.66666667],
       [1.        ],
       [3.        ],
       [3.        ],
       [2.5       ]])

In [68]:
Y_norm = Y - moyenne
Y_norm

array([[ 1.        , -3.        , -1.        ],
       [ 1.        , -1.        , -4.        ],
       [-2.5       ,  1.5       , -1.5       ],
       [ 1.33333333, -0.66666667, -0.66666667],
       [ 0.        ,  0.        , -1.        ],
       [-3.        , -1.        ,  1.        ],
       [ 0.        , -2.        ,  2.        ],
       [-0.5       , -2.5       ,  0.5       ]])

***Forma 2 de calcular Y_norm***

In [70]:
R_sum = R.sum(axis=1)
Y_sum = Y.sum(axis=1)

Y_mean = Y_sum / R_sum
Y_norm = Y - Y_mean.reshape(-1, 1)
Y_norm

array([[ 1.        , -3.        , -1.        ],
       [ 1.        , -1.        , -4.        ],
       [-2.5       ,  1.5       , -1.5       ],
       [ 1.33333333, -0.66666667, -0.66666667],
       [ 0.        ,  0.        , -1.        ],
       [-3.        , -1.        ,  1.        ],
       [ 0.        , -2.        ,  2.        ],
       [-0.5       , -2.5       ,  0.5       ]])

### Question 4 - Afin d'appliquer l'algorithme de filtrage collaboratif, initialiser aléatoirement les deux matrices `X` et `theta` correspondant respectivement aux vecteurs profile des produits et aux vecteurs profile des utilisateurs. Les dimensions de ces deux matrices doivent être choisies adéquatement pour deux paramètres (n=2). Afficher les dimensions de `X` et `theta` à l'aide de la commande `print`.

### ----- Votre réponse ci-dessous -----

In [54]:
n = 2

In [61]:
np.random.seed(2023)
theta = np.random.rand(n_utilisateurs, n)

In [62]:
X = np.random.rand(n_produits, n)

In [63]:
print(f'theta: {theta.shape}')
print(f'X: {X.shape}')

theta: (3, 2)
X: (8, 2)


In [64]:
theta

array([[0.3219883 , 0.89042245],
       [0.58805226, 0.12659609],
       [0.14134122, 0.46789559]])

In [65]:
X

array([[0.02208966, 0.72727471],
       [0.52438734, 0.54493524],
       [0.45637326, 0.50138226],
       [0.39446855, 0.1511723 ],
       [0.36087518, 0.16207701],
       [0.33795869, 0.18032328],
       [0.3909914 , 0.03564821],
       [0.56486165, 0.20346149]])

### Question 5 - À l'aide des fonctions disponibles dans le fichier `helpers.py`, entraînez l'algorithme de filtrage collaboratif. Choisissez une régularisation `L` égale à 1. Quelle est la valeur minimale du coût obtenue ?

### ----- Votre réponse ci-dessous -----

In [73]:
from helpers import cost_reg_func, grad_reg_func

L = 1

parameters = np.vstack([X, theta]).flatten()
cost_reg_func(parameters, *(Y, R, L, n_produits, n_utilisateurs, n))

79.41864322439137

In [74]:
parameters = np.vstack([X, theta]).flatten()
grad_reg_func(parameters, *(Y, R, L, n_produits, n_utilisateurs, n))

array([-1.28920397, -3.02657133, -2.41720455, -3.65679591, -1.79976015,
       -0.29094044, -3.15387303, -5.76048939, -0.32842428, -0.59351056,
       -1.25454174, -1.85457423, -1.67094545, -4.89798955, -0.36150227,
       -2.57590727, -6.20285518, -5.18133216, -4.72288485, -4.02962169,
       -6.17835327, -2.97062753])

In [75]:
from scipy import optimize

initial_parameters = np.vstack([X, theta]).flatten()

model = optimize.fmin_cg(cost_reg_func, initial_parameters, fprime=grad_reg_func, args=(Y_norm, R, L, n_produits, n_utilisateurs, n))

Optimization terminated successfully.
         Current function value: 5.392632
         Iterations: 20
         Function evaluations: 41
         Gradient evaluations: 41


In [77]:
model

array([ 5.48656621e-01,  3.89651108e-01, -1.32670916e-01,  6.64335094e-01,
        8.55118872e-01, -3.32202886e-01,  2.92590978e-01,  7.50283890e-01,
        1.20214598e-06, -2.27051732e-06, -5.70078950e-01,  2.21466754e-01,
       -1.13607870e+00,  4.53336359e-01, -2.74326613e-01, -1.94828339e-01,
        3.78962368e-01,  9.15121937e-01,  9.82154042e-01, -8.48885583e-01,
       -1.31078075e+00,  3.03575269e-02])

### Question 6 - À l'aide de la matrice de bas rang, calculez l'ensemble des prédictions.

### ----- Votre réponse ci-dessous -----

In [83]:
model_ = model.reshape(n_produits+n_utilisateurs, n)
model_

array([[ 5.48656621e-01,  3.89651108e-01],
       [-1.32670916e-01,  6.64335094e-01],
       [ 8.55118872e-01, -3.32202886e-01],
       [ 2.92590978e-01,  7.50283890e-01],
       [ 1.20214598e-06, -2.27051732e-06],
       [-5.70078950e-01,  2.21466754e-01],
       [-1.13607870e+00,  4.53336359e-01],
       [-2.74326613e-01, -1.94828339e-01],
       [ 3.78962368e-01,  9.15121937e-01],
       [ 9.82154042e-01, -8.48885583e-01],
       [-1.31078075e+00,  3.03575269e-02]])

In [84]:
X_trained = model_[:n_produits,:]
X_trained

array([[ 5.48656621e-01,  3.89651108e-01],
       [-1.32670916e-01,  6.64335094e-01],
       [ 8.55118872e-01, -3.32202886e-01],
       [ 2.92590978e-01,  7.50283890e-01],
       [ 1.20214598e-06, -2.27051732e-06],
       [-5.70078950e-01,  2.21466754e-01],
       [-1.13607870e+00,  4.53336359e-01],
       [-2.74326613e-01, -1.94828339e-01]])

In [85]:
theta_trained = model_[n_produits:,:]
theta_trained

array([[ 0.37896237,  0.91512194],
       [ 0.98215404, -0.84888558],
       [-1.31078075,  0.03035753]])

In [86]:
predictions = np.dot(X_trained, theta_trained.T)
predictions

array([[ 5.64498489e-01,  2.08096110e-01, -7.07339693e-01],
       [ 5.57670334e-01, -6.94247760e-01,  1.94070053e-01],
       [ 2.00517241e-02,  1.12186070e+00, -1.13095821e+00],
       [ 7.97482217e-01, -3.49535766e-01, -3.60745858e-01],
       [-1.62223212e-06,  3.10810196e-06, -1.64467710e-06],
       [-1.33693837e-02, -7.47905279e-01,  7.53971696e-01],
       [-1.56730289e-02, -1.50063499e+00,  1.50291227e+00],
       [-2.82251149e-01, -1.04044024e-01,  3.53667537e-01]])

**La recomendacion:**

In [90]:
print(predictions + Y_mean.reshape(-1,1))

[[3.56449849 3.20809611 2.29266031]
 [4.55767033 3.30575224 4.19407005]
 [2.52005172 3.6218607  1.36904179]
 [4.46414888 3.3171309  3.30592081]
 [0.99999838 1.00000311 0.99999836]
 [2.98663062 2.25209472 3.7539717 ]
 [2.98432697 1.49936501 4.50291227]
 [2.21774885 2.39595598 2.85366754]]


In [91]:
Y

array([[4, 0, 2],
       [5, 3, 0],
       [0, 4, 1],
       [5, 3, 3],
       [1, 1, 0],
       [0, 2, 4],
       [3, 1, 5],
       [2, 0, 3]])

In [87]:
predictions[0,:].mean() + Y_mean[0]

3.0217516353477243

In [89]:
Y[0,:].sum() / R[0,:].sum()

3.0

### Question 7 - Calculez et affichez le RMSE.

### ----- Votre réponse ci-dessous -----

In [93]:
from sklearn.metrics import mean_squared_error


mean_squared_error(Y_norm, predictions, squared=False)

1.4694850682587397

In [ ]:
nombre = R.sum(axis=1)
somme = Y.sum(axis=1)
moyenne = (somme / nombre).reshape(-1,1)
moyenne


In [88]:
#res = (predictions[test_0, test_1] - Y_norm[test_0, test_1])
res = (predictions[test_0, test_1] - Y_norm[test_0, test_1])
rss = (res**2).sum()
mse = rss / test_0.shape[0]
rmse = np.sqrt(mse)
rmse

NameError: name 'test_0' is not defined

### Question 8 - Ajoutez un nouvel utilisateur nommé David. Quelle recommandation lui sera faite pour le produit "e" ? Entrainez à nouveau le modèle.

### ----- Votre réponse ci-dessous -----

### Question 9 - Trouver le plus proche voisin du produit "h" à l'aide d'un diagramme en nuage de points. Confirmer la lectture du graphique par une méthode analytique.

### ----- Votre réponse ci-dessous -----