**420-A58-SF - Algorithmes d'apprentissage non supervisé - Hiver 2023 - Spécialisation technique en Intelligence Artificielle**<br/>
MIT License - Copyright (c) 2023 Mikaël Swawola
<br/>

---
# Tutorat - Systèmes de recommandation

On considère la matrice d'utilité Y ci-dessous. Les notes sont données par les utilisateurs Alice, Bob et Eve sur une échelle de 1 à 5. Les produits notés sont nommés a,b,c,d,e,f,g et h.

|   | Alice  | Bob  | Eve  |
|---|---|---|---|
| a  | 4   |   | 2  |
| b  | 5  | 3  |   |
| c  |   | 4  | 1  |
| d  | 5  | 3  | 3  |
| e  | 1  | 1  |   |
| f  |   | 2  | 4  |
| g  | 3  | 1  | 5  |
| h  | 2  |   | 3  |

### Question 1 - À l'aide de Numpy, définir les tableaux `Y` et `R` correspondant à la matrice d'utilité ci-dessus. Afficher ces deux tableaux à l'aide la commande `print`.

### ----- Votre réponse ci-dessous -----

In [1]:
import numpy as np
import pandas as pd

In [40]:
col_names = ['Alice', 'Bob', 'Eve']
Y = np.array([
    [4, 0, 2],
    [5, 3, 0], 
    [0, 4, 1],
    [5,3, 3],
    [1, 1, 0],
    [0, 2, 4],
    [3, 1, 5],
    [2, 0, 3]
]
)

#R = np.where(np.isnan(Y), 0, 1)
R = np.where(Y ==0, 0, 1)


In [41]:
print (Y)
print(R)


[[4 0 2]
 [5 3 0]
 [0 4 1]
 [5 3 3]
 [1 1 0]
 [0 2 4]
 [3 1 5]
 [2 0 3]]
[[1 0 1]
 [1 1 0]
 [0 1 1]
 [1 1 1]
 [1 1 0]
 [0 1 1]
 [1 1 1]
 [1 0 1]]


### Question 2 - Initialiser les variables `n_produits` et `n_utilisateurs` correspondant respectivement au nombre de produits et au nombre d'utilisateurs.

### ----- Votre réponse ci-dessous -----

In [42]:
#n_produits = len(Y)
#n_utilisateurs = len(Y[0,])

n_produits = Y.shape[0]
n_utilisateurs = Y.shape[1]


print(n_produits)
print(n_utilisateurs)

8
3


### Question 3 - Normaliser la matrice `Y` en soustrayant chaque note de la matrice d'utilité par le moyenne des notes. Nommez la matrice normalisée `Y_norm`. Afficher `Y_norm` à l'aide de la commande `print`.

### ----- Votre réponse ci-dessous -----

In [45]:
print(np.mean(Y))
print(np.nanmean(Y))

Y_norm = Y - np.nanmean(Y)
#print(Y_norm)

# Calculate the mean value of Y excluding the 0s
mean_value = np.mean(Y[Y != 0])
print(mean_value)

Y_norm = Y - mean_value
print(Y_norm)

2.1666666666666665
2.1666666666666665
2.888888888888889
[[ 1.11111111 -2.88888889 -0.88888889]
 [ 2.11111111  0.11111111 -2.88888889]
 [-2.88888889  1.11111111 -1.88888889]
 [ 2.11111111  0.11111111  0.11111111]
 [-1.88888889 -1.88888889 -2.88888889]
 [-2.88888889 -0.88888889  1.11111111]
 [ 0.11111111 -1.88888889  2.11111111]
 [-0.88888889 -2.88888889  0.11111111]]


### Question 4 - Afin d'appliquer l'algorithme de filtrage collaboratif, initialiser aléatoirement les deux matrices `X` et `theta` correspondant respectivement aux vecteurs profile des produits et aux vecteurs profile des utilisateurs. Les dimensions de ces deux matrices doivent être choisies adéquatement pour deux paramètres (n=2). Afficher les dimensions de `X` et `theta` à l'aide de la commande `print`.

### ----- Votre réponse ci-dessous -----

In [46]:
n=2

np.random.seed(2023)
X = np.random.rand(n_produits, n)
theta = np.random.rand(n, n_utilisateurs)

print(X.shape)
print(theta.shape)

(8, 2)
(2, 3)


### Question 5 - À l'aide des fonctions disponibles dans le fichier `helpers.py`, entraînez l'algorithme de filtrage collaboratif. Choisissez une régularisation `L` égale à 1. Quelle est la valeur minimale du coût obtenue ?

### ----- Votre réponse ci-dessous -----

In [30]:
from helpers import cost_reg_func, grad_reg_func

In [47]:
#parameters = np.vstack([X, theta])
print(X.shape)
print (theta.shape)

(8, 2)
(2, 3)


In [49]:
parameters = np.vstack([X, theta.T]).flatten()
print(parameters) 

[0.3219883  0.89042245 0.58805226 0.12659609 0.14134122 0.46789559
 0.02208966 0.72727471 0.52438734 0.54493524 0.45637326 0.50138226
 0.39446855 0.1511723  0.36087518 0.16207701 0.33795869 0.03564821
 0.18032328 0.56486165 0.3909914  0.20346149]


In [50]:
L = 1

parameters = np.vstack([X, theta.T]).flatten()
cost_reg_func(parameters, *(Y, R, L, n_produits, n_utilisateurs, n))

83.89843375513206

In [51]:
parameters = np.vstack([X, theta.T]).flatten()
grad_reg_func(parameters, *(Y, R, L, n_produits, n_utilisateurs, n))

array([-1.64426721,  0.40839252, -1.54200467, -1.63869389, -0.85985929,
       -1.80071176, -3.23433324, -1.48858088,  0.14512109,  0.17872016,
       -1.29267606, -1.17866571, -2.60725699, -1.40694425, -1.37678399,
       -0.47963257, -6.06079812, -8.79399637, -3.45299108, -4.68128428,
       -4.9536779 , -6.82022009])

In [52]:
from scipy import optimize

initial_parameters = np.vstack([X, theta.T]).flatten()

model = optimize.fmin_cg(cost_reg_func, initial_parameters, fprime=grad_reg_func, args=(Y_norm, R, L, n_produits, n_utilisateurs, n))

Optimization terminated successfully.
         Current function value: 7.467529
         Iterations: 18
         Function evaluations: 35
         Gradient evaluations: 35


In [54]:
model.shape

(22,)

### Question 6 - À l'aide de la matrice de bas rang, calculez l'ensemble des prédictions.

### ----- Votre réponse ci-dessous -----

In [56]:
model_ = model.reshape(n_produits+n_utilisateurs, n)
model_.shape

(11, 2)

In [57]:
X_trained = model_[:n_produits,:]
X_trained

array([[-0.15927126,  0.60688263],
       [ 0.46589215,  0.80631058],
       [-0.77332092,  0.45714033],
       [ 0.50272835,  0.79331048],
       [ 0.35868206, -1.11531399],
       [ 0.49026528, -0.33163088],
       [ 1.09887885, -0.46396796],
       [-0.13252977, -0.37111691]])

In [58]:
theta_trained = model_[n_produits:,:]
theta_trained

array([[ 0.60105223,  1.54221703],
       [-0.93344902,  0.82693173],
       [ 1.20611469, -0.70810217]])

In [61]:
## Recommendation
predictions = np.dot(X_trained, theta_trained.T)
print(predictions.shape)
predictions + mean_value

(8, 3)


array([[3.72910327, 3.53941099, 2.26705458],
       [4.41242031, 3.12076613, 2.87985798],
       [3.12909224, 3.98876839, 1.63247311],
       [4.41451182, 3.07563121, 2.93349206],
       [1.38441931, 1.63178894, 4.11125684],
       [2.67211713, 2.15701514, 3.71503359],
       [2.83383318, 1.47947167, 4.54279953],
       [2.23688875, 2.70571032, 2.99183148]])

### Question 7 - Calculez et affichez le RMSE.

### ----- Votre réponse ci-dessous -----

In [62]:
from sklearn.metrics import mean_squared_error


mean_squared_error(Y_norm, predictions, squared=False)

1.6333208566985353

### Question 8 - Ajoutez un nouvel utilisateur nommé David. Quelle recommandation lui sera faite pour le produit "e" ? Entrainez à nouveau le modèle.

### ----- Votre réponse ci-dessous -----

### Question 9 - Trouver le plus proche voisin du produit "h" à l'aide d'un diagramme en nuage de points. Confirmer la lectture du graphique par une méthode analytique.

### ----- Votre réponse ci-dessous -----